site_name: Duc Jeremy | Portfolio
repo_url: https://github.com/Toys-R-Us-Rex/Duckify
repo_name: Duckify

theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.follow
  font:
    text: Inter
    code: Roboto Mono
  favicon: assets/logo.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Compétences: competences/index.md
  - Journal:
    - Overview: journal/index.md
    - Week 1: journal/week1.md
    - Week 2: journal/week2.md
    - Week 3: journal/week3.md
    - Week 4: journal/week4.md
